siphon/web/apps/accounts/urls.py
from django.contrib.auth.views import logout
from django.conf.urls import include, url

from siphon.web.apps.accounts.views import LoginView, RegisterView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout')
]

siphon/web/apps/analytics/urls.py
from django.conf.urls import url
from siphon.web.apps.analytics.views import analytics

urlpatterns = [
    url(r'^$', analytics, name='analytics')
]

siphon/web/apps/docs/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView

from siphon.web.apps.docs.views import BaseVersionView

# Note: the index route redirects for quickstart for now, but later
# we'll have a real page index here when more content exists.
urlpatterns = [
    url(r'^$',
        RedirectView.as_view(pattern_name='docs:quickstart', permanent=False),
        name='index'),
    url(r'^quickstart/$',
        TemplateView.as_view(template_name='docs/quickstart.html'),
        name='quickstart'),
    url(r'^build-a-chat-app/$',
        TemplateView.as_view(template_name='docs/chat-app.html'),
        name='chat-app'),
    url(r'^build-a-youtube-browser/$',
        TemplateView.as_view(template_name='docs/youtube-browser.html'),
        name='youtube-browser'),
    url(r'^run-react-native-on-device/$',
        TemplateView.as_view(template_name='docs/run-on-device.html'),
        name='run-on-device'),
    url(r'^faq/$',
        TemplateView.as_view(template_name='docs/faq.html'),
        name='faq'),
    url(r'^facebook-sdk/$',
        TemplateView.as_view(template_name='docs/facebook-sdk.html'),
        name='facebook-sdk'),
    url(r'^team-sharing/$',
        TemplateView.as_view(template_name='docs/team-sharing.html'),
        name='team-sharing'),
    url(r'^beta-testing/$',
        TemplateView.as_view(template_name='docs/beta-testing.html'),
        name='beta-testing'),
    url(r'^existing-react-native-app/$',
        TemplateView.as_view(
            template_name='docs/existing-react-native-app.html'),
        name='existing-react-native-app'),
    url(r'^base-version/$', BaseVersionView.as_view(), name='base-version')
]

siphon/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required


def static_url(regex, name, authenticated=False):
    view = TemplateView.as_view(template_name='%s.html' % name)
    if authenticated:
        view = login_required(view)
    return url(regex, view, name=name)

static_urls = [
    static_url(r'^$', 'landing'),
    static_url(r'^dashboard/$', 'dashboard', authenticated=True),
    static_url(r'^contact-us/$', 'contact'),
    static_url(r'^pricing/$', 'pricing'),
    static_url(r'^terms-of-use/$', 'terms-of-use'),
    static_url(r'^privacy-policy/$', 'privacy-policy'),
    static_url(r'^android-launch/$', 'android-launch')
]

urlpatterns = [
    url('', include(static_urls, namespace='static')),
    url(r'^docs/', include('siphon.web.apps.docs.urls',
        namespace='docs')),
    url(r'^accounts/', include('siphon.web.apps.accounts.urls',
        namespace='accounts')),
    url(r'^subscriptions/', include('siphon.web.apps.subscriptions.urls',
        namespace='subscriptions')),
    url(r'^analytics/', include('siphon.web.apps.analytics.urls',
        namespace='analytics')),
    url(r'^permissions/', include('siphon.web.apps.permissions.urls',
        namespace='permissions')),

    # API
    url(r'^api/v1/', include('siphon.web.api_urls', namespace='api')),

    # App Store shortcut alias
    url(r'^i/?$', RedirectView.as_view(
        url='https://itunes.apple.com/us/app/siphon-sandbox/id1059664078',
        permanent=False
    )),

    # Play Store shortcut alias
    url(r'^a/?$', RedirectView.as_view(
        url='https://play.google.com/store/apps/details?id=com.getsiphon.siphonbase',
        permanent=False
    )),

    # Third-party
    url(r'^drip/', include('drip.urls', namespace='drip')),

    # Here be dragons
    url(r'^bananas/', include(admin.site.urls))
]

siphon/web/apps/analytics/views.py
import arrow

import json

from django.http import Http404
from django.views.decorators.http import require_http_methods
from django.shortcuts import render
from django.contrib.auth.models import User

def get_weeks(start=None):
    # Get the very first join date
    dt = User.objects.order_by('date_joined').first().date_joined
    default_start = arrow.get(dt).replace(weeks=+1)
    if start is None:
        start = default_start
    start = start.floor('week')  # make sure its a Monday
    # Protect against divide by zero
    if start < default_start:
        start = default_start
    start = start.floor('week')  # make sure its a Monday
    # Return a range of mondays
    end = arrow.now().replace(weeks=+1).floor('week')
    return arrow.Arrow.range('week', start=start, end=end)

def weekly_user_growth():
    if User.objects.count() < 1:
        return []

    # Get the weekly user counts
    user_counts = []
    weeks = get_weeks(start=arrow.Arrow(2016, 1, 11))  # avoid the crazy days
    for dt in weeks:
        x = dt.datetime
        c = User.objects.filter(date_joined__lte=x).count()
        user_counts.append(c)

    data = []
    percentages = [100.0 * a1 / a2 - 100 for a1, a2 in
                   zip(user_counts[1:], user_counts)]
    for i, perc in enumerate(percentages):
        week_name = weeks[i + 1].format('YYYY-MM-DD')
        data.append([week_name, perc, 10])
    return data

def cumulative_users():
    weeks = get_weeks()
    data = []
    for dt in weeks:
        x = dt.datetime
        c = User.objects.filter(date_joined__lte=x).count()
        data.append([dt.format('YYYY-MM-DD'), c])
    return data

@require_http_methods(['GET'])
def analytics(request):
    if not request.user or not request.user.is_staff:
        raise Http404()

    return render(request, 'analytics.html', {
        'weekly_user_growth': json.dumps(weekly_user_growth()),
        'cumulative_users': json.dumps(cumulative_users())
    })

templates/includes/analytics.html
<script type="text/javascript">
{% if SIPHON_ENV == 'production' %}
// Google Analytics
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
if (ga !== undefined) {
    ga('create', 'UA-71618181-1', 'auto');
    ga('send', 'pageview');
}
{% endif %}

// Mixpanel
{% if SIPHON_ENV == 'production' %}
(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
{% else %}
window.mixpanel = {
    track: function() {
        console.log('[mixpanel.track]', arguments[0]);
        if (arguments.length > 2) {
            var cb = arguments[2];
            cb();
        }
    },
    init: function() {},
    track_links: function() { console.log('[mixpanel.track_links]', arguments);},
    alias: function(a) { console.log('[mixpanel.alias]', a); },
    identify: function(a) { console.log('[mixpanel.identify]', a); }
};
{% endif %}
// Ghostery fix
if (window.mixpanel === undefined) {
    window.mixpanel = {
        track: function() {
            if (arguments.length > 2) {
                var cb = arguments[2];
                cb();
            }
        },
        init: function() {},
        track_links: function() {},
        alias: function() {},
        identify: function() {}
    };
}
// Initialise mixpanel
mixpanel.init('c3a111fe44df4fa1df943af18dd2464b');
{% if request.user.is_authenticated and not no_identify %}
mixpanel.identify('{{ request.user.username }}');
{% endif %}
</script>

templates/includes/base.html
{% load compress static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Siphon{% endblock %}</title>
    <link rel="apple-touch-icon" href="{% static "img/apple-touch-icon.png" %}" />
    <link rel="icon" type="image/png" href="{% static "img/favicon.png" %}" sizes="32x32" />
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static "lib/normalize.css" %}" />
    <link rel="stylesheet" type="text/x-scss" href="{% static "css/main.scss" %}" />
    {% endcompress %}
    {% compress css %}
    {% block css %}{% endblock %}
    {% endcompress %}
    {% include "includes/analytics.html" %}
  </head>
  <body>
      <div class="shutdown">
          <span class="shutdown__headline">Siphon is shutting down on 27th July 2016.</span>
          <span class="shutdown__text">
              <strong>To our customers, users and supporters:</strong> unfortunately this is the end of the road for Siphon. Our long-term goal was to create the most developer friendly end-to-end publishing platform for mobile apps.
              <br /><br />Due to some inherent limitations in the early design decisions that we made (in particular the inability to compile your own native modules with Siphon) we have come to the regrettable conclusion that this vision is not possible at this time. We hoped that these native bridged modules would mature and become less important over time, but this has turned out to not be the case.
              <br /><br />All apps created using Siphon are fully compatible with the standard React Native framework and transferring your app should only take a few minutes.
              Please <a href="mailto:hello@getsiphon.com" style="color: white;"><strong>email us</strong></a> if you need any help migrating your app.
              <br /><br /><strong>Thanks to everyone who supported us over the past few months.</strong>
          </span>
      </div>
    {% block content %}{% endblock %}
    <div class="footer">
        <div>
            <div>
                <a href="/">Home</a>
                <a href="/blog/">Blog</a>
                <a href="{% url 'static:pricing' %}">Pricing</a>
            </div>
            <div>
                <a href="{% url 'docs:index' %}">Docs</a>
                <a href="{% url 'static:terms-of-use' %}">Terms of Use</a>
                <a href="{% url 'static:privacy-policy' %}">Privacy Policy</a>
            </div>
            <div>
                <a href="https://twitter.com/getsiphon" style="font-weight: bold;">Twitter</a>
                <a href="https://www.facebook.com/getsiphon" style="font-weight: bold;">Facebook</a>
                <a href="{% url 'static:contact' %}">Contact us</a>
            </div>
            <span>&copy; Siphon</span>
        </div>
    </div>
  </body>
</html>

templates/includes/header.html
{% load static %}
<div class="header">
    <div>
        <a href="/" class="header__logo">
            <img src="{% static "img/landing/logo.png" %}" width="127" height="39" />
        </a>
        {% if title %}
        <div class="header__title">/{{ title|lower }}</div>
        {% endif %}
        <div class="header__links">
            {% if request.user.is_authenticated %}
            <a href="{% url 'static:dashboard' %}"{% if '/dashboard/' in request.path %} class="header__active-link"{% endif %}>Dashboard</a>
            {% endif %}
            <a href="{% url 'docs:faq' %}"{% if '/docs/faq/' in request.path %} class="header__active-link"{% endif %}>FAQ</a>
            <a href="{% url 'docs:index' %}"{% if '/docs/quickstart/' in request.path %} class="header__active-link"{% endif %}>Docs</a>
            <a href="/blog/">Blog</a>
            <a href="{% url 'static:contact' %}"{% if '/contact-us/' in request.path %} class="header__active-link"{% endif %}>Contact us</a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Log out</a>
            {% else %}
            <a href="{% url 'accounts:login' %}">Log in</a>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/landing_header.html
{% load static %}
<div class="landing-header">
    <div>
        <a href="/"><img src="{% static "img/landing/logo.png" %}" width="127" height="39" /></a>
        <div class="landing-header__links">
            <a href="{% url 'docs:faq' %}">FAQ</a>
            <a href="{% url 'docs:index' %}">Docs</a>
            <a href="/blog/">Blog</a>
            <a href="{% url 'static:pricing' %}"{% if '/pricing' in request.path %} class="landing-header__active-link"{% endif %}>Pricing</a>
            <a href="{% url 'static:contact' %}">Contact us</a>
            {% if request.user.is_authenticated %}
            <a class="landing-header__links__dashboard" href="{% url 'static:dashboard' %}">Dashboard</a>
            {% else %}
            <a class="landing-header__links__login" href="{% url 'accounts:login' %}">Log in</a>
            {% endif %}
        </div>
    </div>
</div>