siphon/web/apps/accounts/urls.py
from django.contrib.auth.views import logout
from django.conf.urls import include, url

from siphon.web.apps.accounts.views import LoginView, RegisterView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout')
]

siphon/web/apps/docs/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView

from siphon.web.apps.docs.views import BaseVersionView

# Note: the index route redirects for quickstart for now, but later
# we'll have a real page index here when more content exists.
urlpatterns = [
    url(r'^$',
        RedirectView.as_view(pattern_name='docs:quickstart', permanent=False),
        name='index'),
    url(r'^quickstart/$',
        TemplateView.as_view(template_name='docs/quickstart.html'),
        name='quickstart'),
    url(r'^build-a-chat-app/$',
        TemplateView.as_view(template_name='docs/chat-app.html'),
        name='chat-app'),
    url(r'^build-a-youtube-browser/$',
        TemplateView.as_view(template_name='docs/youtube-browser.html'),
        name='youtube-browser'),
    url(r'^run-react-native-on-device/$',
        TemplateView.as_view(template_name='docs/run-on-device.html'),
        name='run-on-device'),
    url(r'^faq/$',
        TemplateView.as_view(template_name='docs/faq.html'),
        name='faq'),
    url(r'^facebook-sdk/$',
        TemplateView.as_view(template_name='docs/facebook-sdk.html'),
        name='facebook-sdk'),
    url(r'^team-sharing/$',
        TemplateView.as_view(template_name='docs/team-sharing.html'),
        name='team-sharing'),
    url(r'^beta-testing/$',
        TemplateView.as_view(template_name='docs/beta-testing.html'),
        name='beta-testing'),
    url(r'^existing-react-native-app/$',
        TemplateView.as_view(
            template_name='docs/existing-react-native-app.html'),
        name='existing-react-native-app'),
    url(r'^base-version/$', BaseVersionView.as_view(), name='base-version')
]

siphon/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required


def static_url(regex, name, authenticated=False):
    view = TemplateView.as_view(template_name='%s.html' % name)
    if authenticated:
        view = login_required(view)
    return url(regex, view, name=name)

static_urls = [
    static_url(r'^$', 'landing'),
    static_url(r'^dashboard/$', 'dashboard', authenticated=True),
    static_url(r'^contact-us/$', 'contact'),
    static_url(r'^pricing/$', 'pricing'),
    static_url(r'^terms-of-use/$', 'terms-of-use'),
    static_url(r'^privacy-policy/$', 'privacy-policy'),
    static_url(r'^android-launch/$', 'android-launch')
]

urlpatterns = [
    url('', include(static_urls, namespace='static')),
    url(r'^docs/', include('siphon.web.apps.docs.urls',
        namespace='docs')),
    url(r'^accounts/', include('siphon.web.apps.accounts.urls',
        namespace='accounts')),
    url(r'^subscriptions/', include('siphon.web.apps.subscriptions.urls',
        namespace='subscriptions')),
    url(r'^analytics/', include('siphon.web.apps.analytics.urls',
        namespace='analytics')),
    url(r'^permissions/', include('siphon.web.apps.permissions.urls',
        namespace='permissions')),

    # API
    url(r'^api/v1/', include('siphon.web.api_urls', namespace='api')),

    # App Store shortcut alias
    url(r'^i/?$', RedirectView.as_view(
        url='https://itunes.apple.com/us/app/siphon-sandbox/id1059664078',
        permanent=False
    )),

    # Play Store shortcut alias
    url(r'^a/?$', RedirectView.as_view(
        url='https://play.google.com/store/apps/details?id=com.getsiphon.siphonbase',
        permanent=False
    )),

    # Third-party
    url(r'^drip/', include('drip.urls', namespace='drip')),

    # Here be dragons
    url(r'^bananas/', include(admin.site.urls))
]

siphon/web/apps/docs/views.py
from django.views.generic.base import TemplateView
from siphon.web.apps.apps.models import BaseVersion


class BaseVersionView(TemplateView):
    template_name = 'docs/base-version.html'

    def get_context_data(self, **kwargs):
        context = super(BaseVersionView, self).get_context_data(**kwargs)
        context['base_versions'] = BaseVersion.objects.all().order_by('-name')
        return context

templates/docs/base.html
{% extends "includes/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/x-scss" href="{% static "css/docs.scss" %}" />
<link rel="stylesheet" type="text/css" href="{% static "lib/prismjs/prism.css" %}" />
{% endblock %}

{% block content %}
{% include "includes/header.html" with title="Docs" %}
<div class="docs">
    {% include "docs/includes/index.html" %}
    <div class="docs__content">
        {% block docs_content %}{% endblock %}
    </div>
    <div class="docs__sidebar">
        <div class="docs__sidebar__contents">
            <span>Table of contents</span>
            {% block docs_toc %}{% endblock %}
        </div>
        <div class="docs__sidebar__section">
            <span>Watch the video</span>
            <a class="docs__sidebar__video" href="https://www.youtube.com/watch?v=0Nvnc95CR5w" target="_blank">
                <img src="{% static "img/docs/video-thumb.png" %}" width="182" height="119" />
            </a>
        </div>
        <div class="docs__sidebar__section">
            <span>Learn more</span>
            <a href="{% url 'docs:quickstart' %}">Quickstart</a>
            <a href="{% url 'docs:faq' %}">Read the FAQ</a>
            <a href="{% url 'docs:faq' %}#native-modules">Native modules</a>
            <a href="{% url 'docs:base-version' %}">All about base versions</a>
        </div>
    </div>
</div>
<div class="docs__responsive-index">
    <div class="docs__subheading">More docs</div>
    {% include "docs/includes/index.html" %}
</div>
<script src="{% static "lib/prismjs/prism.js" %}"></script>
{% endblock %}

templates/docs/chat-app.html
{% extends "docs/base.html" %}
{% load static %}

{% block title %}Build a real-time chat app with Siphon | Siphon Docs{% endblock %}

{% block docs_toc %}
<a href="#create-app">Create a new Siphon app</a>
<a href="#add-user-interface">Add a simple user interface</a>
<a href="#websocket">Receiving chat messages with a websocket</a>
<a href="#mutating-state">Mutating state with incoming chat messages</a>
<a href="#sending-messages">Sending chat messages</a>
<a href="#next-up">Next up</a>
<a href="#"></a>
{% endblock %}

{% block docs_content %}
    <div class="docs__headline">Build a real-time chat app with Siphon</div>
    <p>We're going to build a simple real-time chat application using React Native.
    Follow the <a href="{% url 'docs:quickstart' %}">quickstart tutorial</a> first if
    you haven't yet set up your machine to use Siphon.</p>

    <p><a class="docs__content__button" href="{% url 'docs:quickstart' %}">Install the command-line tool</a></p>

    <a name="create-app"></a>
    <div class="docs__subheading">Create a new Siphon app</div>
    <p>Navigate to a suitable directory (anywhere is fine) and type the following
    command to create a new app:</p>
    <div class="docs__code"><span>$ </span>siphon create chat-app</div>
    <p>You can call it anything you like, but for the rest of this tutorial we will refer to the app as <strong>chat-app</strong>.</p>
    <p>A new directory containing the basic app template will be created on your local machine and the files will be pushed to our servers.</p>
    <p>Open up the <a href="/a" target="_blank">Siphon Sandbox</a> app on your iOS device and <strong>tap the new app icon</strong> to run it.</p>
    <div class="docs__content__help-section">
        <span>
            The app directory works like a typical Node.js project directory; you can install <br />
            suitable third-party modules using <span class="docs__technical">npm install</span>
            and the command-line tool will push the <span class="docs__technical">node_modules</span> directory and bundle it with your app.
        </span>
    </div>

    <a name="add-user-interface"></a>
    <div class="docs__subheading">Add a simple user interface</div>
    <p>We're going to alter the template app that we just created. Open up the file called
    <span class="docs__technical">chat-app/index.js</span> in your favourite editor.</p>
    <p>Lets add a minimal user interface ready for sending and receiving chat messages.
    Remove the contents of that file and paste in the following code:</p>
    {% include "docs/snippets/user-interface.html" %}
    <p>Later we'll use a websocket to connect to the server
    and append incoming messages to the <span class="docs__technical">messages</span> state, but
    for now the UI is going to look quite empty.</p>
    <p>Save the file and push your changes to Siphon:</p>
    <div class="docs__code"><span>$ </span>siphon push</div>
    <p>The app will reload itself and you should see something like this:</p>
    <img class="docs__content__chat-ui-image" src="{% static "img/docs/chat-app/screenshot-only-ui.png" %}" width="254" height="450" />

    <a name="websocket"></a>
    <div class="docs__subheading">Receiving chat messages with a websocket</div>
    <p>We're going to use the <span class="docs__technical">WebSocket</span> class
    provided by React Native to send and receive chat messages.</p>
    <p>First we will only log incoming messages to the console. Add these two methods to your
    <span class="docs__technical">App</span> class definition:</p>
    {% include "docs/snippets/websocket.html" %}
    <p>After the <span class="docs__technical">App</span> component gets rendered, its going to
    open up a socket and start printing incoming messages to the console.</p>
    <p>Open up a separate terminal window and leave it streaming the logs from your app:</p>
    <div class="docs__code">
        <span>$ </span>cd chat-app<br />
        <span>$ </span>siphon logs
    </div>
    <p>Now save the file and switch back to the other terminal window to push the changes:</p>
    <div class="docs__code"><span>$ </span>siphon push</div>
    <p>You should see some log output in the new terminal window. If there are other Siphon users
    currently chatting, you may see some incoming messages in the logs.</p>
    <div class="docs__content__help-section">
        <span>
            We set up a shared Node.js chat server at <span class="docs__technical">siphon-chat.herokuapp.com</span>.
            When you've finished the app, you get to chat to everyone else taking this tutorial too!
        </span>
    </div>

    <a name="mutating-state"></a>
    <div class="docs__subheading">Mutating state with incoming chat messages</div>
    <p>Let's make a small change so that incoming chat messages are displayed in the UI.
    Replace the definition of <span class="docs__technical">componentDidMount</span> with this one:</p>
    {% include "docs/snippets/mutate-state.html" %}
    <p>Push your changes and run the app in the sandbox:</p>
    <div class="docs__code"><span>$ </span>siphon push</div>
    <p>Any incoming chat messages will now be displayed visually.</p>

    <a name="sending-messages"></a>
    <div class="docs__subheading">Sending chat messages</div>
    <p>Lets hook up the <span class="docs__technical">&#x3C;TextInput&#x3E;</span> component so that it
    broadcasts its contents to the chat server when we hit send.</p>
    <p>Replace the empty definition of <span class="docs__technical">handleSubmit</span> with this one:</p>
    {% include "docs/snippets/handle-submit.html" %}
    <p>Now when you hit send, it sends the message across the websocket that we created earlier and then
    clears the contents of the <span class="docs__technical">&#x3C;TextInput&#x3E;</span>.</p>
    <p>Push your changes and open the app. It should look like this:</p>
    <img class="docs__content__chat-ui-image" src="{% static "img/docs/chat-app/screenshot-full.png" %}" width="254" height="450" />
    <div class="docs__content__help-section">
        <span>
            Complete source code for this app is
            <a href="https://github.com/getsiphon/siphon-chat" target="_blank">available on GitHub</a>.
        </span>
    </div>
    <p>That's the end of the tutorial, thanks for following along.</p>

    <a name="next-up"></a>
    <div class="docs__subheading">Next up</div>
    <p class="docs__content__next-buttons">
        <a class="docs__content__next-button" href="{% url 'docs:youtube-browser' %}">Build a YouTube browser</a>
        <a class="docs__content__next-button" href="{% url 'docs:faq' %}">FAQs</a>
        <a class="docs__content__next-button" href="{% url 'docs:faq' %}#publishing">How to publish an app</a>
    </p>
    <script type="text/javascript">
        mixpanel.track('Web: Docs/Chat');
    </script>
{% endblock %}

templates/docs/facebook-sdk.html
{% extends "docs/base.html" %}
{% load static %}

{% block title %}Using Facebook's SDK with Siphon | Siphon Docs{% endblock %}

{% block docs_toc %}
<a href="#register-app">Register your app</a>
<a href="#add-platform">Add platform</a>
<a href="#configure-project">Configure your project</a>
<a href="#next-up">Next up</a>
{% endblock %}

{% block docs_content %}
    <div class="docs__headline">Using Facebook's SDK with Siphon</div>
    <p>Siphon now supports Facebook's
      <a href="https://github.com/facebook/react-native-fbsdk" target="_blank">react-native-fbsdk</a> module.
      With minimal configuration, you can now integrate your Siphon app with Facebook.
    </p>

    <p>We'll assume you have already created a Siphon app and are ready to use
    Facebook's SDK. Please follow the
    <a href="{% url 'docs:quickstart' %}">quickstart tutorial</a> first if
    you haven't yet set up your machine to use Siphon.</p>

    <p><strong>Note:</strong> This module is not supported in the sandbox and is currently available for
    iOS only. Android support is coming soon.</p>

    <div class="docs__content__help-section">
        <span>
            The <span class="docs__technical">react-native-fbsdk</span> module is available
            for <span class="docs__technical">base_version</span> 0.5 or higher. Click
            <a href="{% url 'docs:base-version' %}">here</a> to learn more about base versions.
        </span>
    </div>

    <a name="register-app"></a>
    <div class="docs__subheading">Register your app with Facebook</div>
    <p>Before you can use the <span class="docs__technical">react-native-fbsdk</span>
      module in your project you need to register your app with Facebook.</p>

    <p>Log in to your
    <a href="https://developers.facebook.com" target="_blank">Facebook Developer account</a>
    and create a new app. Click 'basic setup' to proceed.</p>

    <img class="docs__content__screenshot" src="{% static "img/docs/facebook-sdk/create-app.png" %}" width="600"/>

    <p>Fill in the 'Contact Email' field and select an appropriate category for your app.
    When you're done, click 'Create App ID'.</p>

    <img class="docs__content__screenshot" src="{% static "img/docs/facebook-sdk/create-app-id.png" %}" width="600"/>

    <a name="add-platform"></a>
    <div class="docs__subheading">Add platform</div>

    <p>You need to specify any platforms you wish to support in the 'Settings' section
      of your app's dashboard on the
      <a href="https://developers.facebook.com" target="_blank">Facebook Developer site</a>.</p>
    <p><strong>iOS</strong></p>
    <p>
    Navigate to the 'Settings' section of your app's dashboard, click the 'Add Platform' button
    and select 'iOS'.</p>
    <img class="docs__content__screenshot" src="{% static "img/docs/facebook-sdk/add-platform.png" %}" width="600"/>
    <img class="docs__content__screenshot" src="{% static "img/docs/facebook-sdk/select-platform.png" %}" width="600"/>

    <p>
      You need to provide the Bundle ID of your app,
      which is of the form <span class="docs__technical">com.getsiphon.{siphon-app-id}</span>
      where <span class="docs__technical">{siphon-app-id}</span> is replaced with your app's <span class="docs__technical">app_id</span>.
      Your app's <span class="docs__technical">app_id</span> is generated by Siphon and is distinct from
      the app ID generated by Facebook on their Developer site.
    </p>

    <p>
      To find your app's <span class="docs__technical">app_id</span>, navigate to your app's directory
      and open the <span class="docs__technical">.siphon</span> file with a text editor. The <span class="docs__technical">{siphon-app-id}</span>
      corresponds to the value of the <span class="docs__technical">app_id</span> field.
    </p>
    <p>
      For example, if your <span class="docs__technical">.siphon</span> file looks like this:
    </p>

    {% include "docs/snippets/facebook-sdk/dot-siphon.html" %}

    <p>
     The app's Bundle ID is <span class="docs__technical">com.getsiphon.adMw1E4yAQ</span>.
    </p>

    <p>Fill in the 'Bundle ID' field of the 'iOS' form. The other fields may be left blank for now.</p>

    <img class="docs__content__screenshot" src="{% static "img/docs/facebook-sdk/ios-settings.png" %}"/>

    <div class="docs__content__help-section">
        <span>
            <strong>Important:</strong> The 'iPhone Store ID' is generated by Apple when you submit your app to the App Store. Log in to your
            iTunes Connect account after submitting your app to retrieve this ID, then return to the Facebook
            Developer site to complete this form.
        </span>
    </div>

    <p><strong>Android</strong></p>

    <p>Android support is coming soon.</p>

    <a name="configure-project"></a>
    <div class="docs__subheading">Configure your project</div>

    <p>You now need to add the app ID created by Facebook to your app's <span class="docs__technical">Siphonfile</span>.
    You can find the app ID on your app's dashboard on the <a href="https://developers.facebook.com" target="_blank">Facebook Developer site</a>.</p></p>

    <img class="docs__content__screenshot" src="{% static "img/docs/facebook-sdk/app-id.png" %}"/>

    <p>Add the <span class="docs__technical">facebook_app_id</span>
    to the <span class="docs__technical">Siphonfile</span> in your app's directory
    and make sure the <span class="docs__technical">display_name</span>
    matches the one in your app's settings on Facebook's Developer site.
    Your <span class="docs__technical">Siphonfile</span> should look something like this:</p>

    {% include "docs/snippets/facebook-sdk/siphonfile.html" %}

    You can now use the <span class="docs__technical">react-native-fbsdk</span> module in your app!

    <a name="next-up"></a>
    <div class="docs__subheading">Next up</div>
    <p class="docs__content__next-buttons">
        <a class="docs__content__next-button" href="{% url 'docs:chat-app' %}">Build a real-time chat app</a>
        <a class="docs__content__next-button" href="{% url 'docs:faq' %}">FAQs</a>
        <a class="docs__content__next-button" href="{% url 'docs:base-version' %}">How base versions work</a>
    </p>
<script type="text/javascript">
    mixpanel.track('Web: Docs/FacebookSDK');
</script>
{% endblock %}

templates/docs/quickstart.html
{% extends "docs/base.html" %}
{% load static %}

{% block title %}Quickstart | Siphon Docs{% endblock %}

{% block docs_toc %}
<a href="#install-cli">Install the command-line client</a>
<a href="#download-sandbox">Download and run the Siphon Sandbox app</a>
<a href="#create-app">Create your first app</a>
<a href="#push-changes">Push some changes to your app</a>
<a href="#running-in-the-simulator">Running your app in the simulator</a>
<a href="#beta-testing">Sharing your app with beta testers</a>
<a href="#publishing">Publishing your app</a>
<a href="#next-up">Next up</a>
{% endblock %}

{% block docs_content %}
    <div class="docs__headline">Quickstart</div>
    <p>Siphon is primarily a command-line tool. This quickstart tutorial will
    walk you through the installation process and then describe all
    of the ways that you can interact with the service.</p>

    <a name="install-cli"></a>
    <div class="docs__subheading">Install the command-line client</div>
    <p>To get started with Siphon you will need to download our lightweight command-line tool. Paste the following command into a terminal window:</p>
    <div class="docs__code"><span>$ </span>curl https://getsiphon.com/install.sh | sh</div>
    <p>The installer script will take a few seconds to complete. Once that's done, check that the tool is working:</p>
    <div class="docs__code"><span>$ </span>siphon --help</div>
    <div class="docs__content__help-section">
        <a href="http://blog.teamtreehouse.com/introduction-to-the-mac-os-x-command-line" target="_blank">Read a beginners guide to using the terminal</a>
    </div>

    <a name="download-sandbox"></a>
    <div class="docs__subheading">Download and run the Siphon Sandbox app</div>
    <p>One way to run apps is by installing the Siphon Sandbox app onto your device. Open up your phone's browser and type in <thead>
      the following address if it's an <strong>iPhone</strong>:</thead></p>
    <div>
      <a class="docs__content__big-link" href="https://getsiphon.com/i">getsiphon.com/i</a>
    </div>
    <p>Or, if it's an <strong>Android</strong> device:</p>
    <div>
      <a class="docs__content__big-link" href="https://getsiphon.com/a">getsiphon.com/a</a>
    </div>
    <p>Once that's done, login with your Siphon account. No account yet?</p>
    <p><a class="docs__content__button" href="{% url 'accounts:register' %}?from_tutorial=1">Create a free account</a></p>
    <p>You can also use the <span class="docs__technical">siphon play</span> command to run your apps in the simulator. More on that below.</p>
    <div class="docs__content__help-section">
        <span>You can run both iOS and Android apps through our sandbox app. Android simulator support
        is coming soon.</span>
    </div>

    <a name="create-app"></a>
    <div class="docs__subheading">Create your first app</div>
    <img class="docs__content__create-app-image" src="{% static "img/docs/quickstart/create-app.png" %}" width="251" height="213" />
    <p>Navigate to a suitable directory (anywhere is fine) and type the following
    command to create a new app:</p>
    <div class="docs__code" style="display: inline-block;"><span>$ </span>siphon create my-app</div>
    <div class="docs__code-sublink">
        <a href="{% url 'docs:existing-react-native-app' %}">How do I convert an existing React Native app?</a>
    </div>
    <p>You can name the app anything you like. The tool creates a new directory with same name.</p>
    <div>
        <p>The new directory contains a simple React Native template app. Once the command finishes
        running, the new app is going to appear in the Siphon Sandbox.</p>
        <p>Next, <strong>tap on the icon</strong> to start the app; it's going to load over-the-air.</p>
    </div>

    <a name="push-changes"></a>
    <div class="docs__subheading">Push some changes to your app</div>
    <p>Now let's try making some changes. Navigate into the newly created
    directory and open up <span class="docs__technical">index.js</span> in
    your favourite editor.</p>
    <p>Change some of the template text within the <span class="docs__technical">&#x3C;Text&#x3E;</span> tag and save the file.</p>
    <div class="docs__content__push-changes-image">
        <img src="{% static "img/docs/quickstart/push-changes.gif" %}" width="753" height="289" />
    </div>
    <div class="docs__content__react-native-blurb">
        <span>Siphon apps are powered by React Native under the hood. Learn more <br />about it here:
        <a href="http://www.toptal.com/ios/cold-dive-into-react-native-a-beginners-tutorial" target="_blank">React Native: A Beginner's Tutorial</a></span>
    </div>
    <p>Next, push your changes with the command-line tool:</p>
    <div class="docs__code">
        <span>$ </span>siphon push
    </div>
    <p>The app should now automatically reload on the phone and display your changes. Instead of typing in this
    command for every change, you can also use the tool to <strong>watch</strong> your app for changes:</p>
    <div class="docs__code">
        <span>$ </span>siphon push --watch
    </div>
    <p>Every time you save a change to one of your app's files, the tool will push those changes automatically. This
    makes the process of developing your app much more pleasant.</p>
    <p>To stream logs and errors from your app as it runs in the sandbox, you can use the
    <span class="docs__technical">siphon logs</span> command.
    <div class="docs__content__help-section">
        <span>
            The app directory works like a typical Node.js project directory; you can install <br />
            suitable third-party modules using <span class="docs__technical">npm install</span>
            and the command-line tool will push the <span class="docs__technical">node_modules</span> directory and bundle it with your app.
        </span>
    </div>

    <a name="running-in-the-simulator"></a>
    <div class="docs__subheading">Running your app in the simulator</div>
    <p>If you're using a Mac, there's a way to run your app in the iOS simulator. Navigate to your app directory
    and type in:</p>
    <div class="docs__code">
        <span>$ </span>siphon develop
    </div>
    <p>The tool will prompt you to install Xcode and any other necessary components that you haven't already
    installed on your local machine.</p>
    <p>It will then build and run your project as a standalone app in the simulator
    while running the React Native packager in the background (so you get the benefits of
    <a href="https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html">Hot Reloading</a>).</p>
    <p>You can specify other simulator types like this:</p>
    <div class="docs__code">
        <span>$ </span>siphon develop --simulator ipad2
    </div>
    <p style="color:#aaaaaa">Soon you will also be able to run your app in the Android emulator, but for
    now you should use the <a href="/a">sandbox</a>.</p>
    <div class="docs__content__help-section">
        <span>To run an app on your developer device you should use
        <a href="{% url 'docs:run-on-device' %}">siphon play</a>.</span>
    </div>

    <a name="beta-testing"></a>
    <div class="docs__subheading">Sharing your app with beta testers</div>
    <p>Before publishing an app it can be useful to send it to beta testers so that they can give you feedback.
    Simply specify an email address and we will send them an invitation
    to beta test your app:</p>
    <div class="docs__code">
        <span>$ </span>siphon share someone@domain.com
    </div>
    <p>No approval is required and the recipient will be prompted to create a
    Siphon account if they do not already have one. The user will see a special read-only copy of your app and
    you can instantly send them <a href="{% url 'docs:beta-testing' %}#sharing-changes">changes</a> as often
    as you like.</p>
    <p><a href="{% url 'docs:beta-testing' %}">Learn more about beta testing</a></p>

    <a name="publishing"></a>
    <div class="docs__subheading">Publishing your app</div>
    <p>When you're finished working on an app, you can publish it by typing in one command:</p>
    <div class="docs__code">
        <span>$ </span>siphon publish --platform ios
    </div>
    <p>You will be prompted to enter some basic information about your app, like a description and some keywords.</p>
    <p>Behind-the-scenes we will build, sign, package and submit an app binary on your behalf.</p>
    <p><a href="{% url 'docs:faq' %}#publishing">Read more about how publishing works</a></p>
    <div class="docs__content__help-section">
        <span>
            Publishing to the App Store and Google Play requires a
            <a href="{% url 'static:pricing' %}">paid subscription</a>.
        </span>
    </div>

    <a name="next-up"></a>
    <div class="docs__subheading">Next up</div>
    <p class="docs__content__next-buttons">
        <a class="docs__content__next-button" href="{% url 'docs:chat-app' %}">Build a real-time chat app</a>
        <a class="docs__content__next-button" href="{% url 'docs:faq' %}">FAQs</a>
    </p>
<script type="text/javascript">
    mixpanel.track('Web: Docs/Quickstart');
</script>
{% endblock %}