siphon/web/apps/docs/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView

from siphon.web.apps.docs.views import BaseVersionView

# Note: the index route redirects for quickstart for now, but later
# we'll have a real page index here when more content exists.
urlpatterns = [
    url(r'^$',
        RedirectView.as_view(pattern_name='docs:quickstart', permanent=False),
        name='index'),
    url(r'^quickstart/$',
        TemplateView.as_view(template_name='docs/quickstart.html'),
        name='quickstart'),
    url(r'^build-a-chat-app/$',
        TemplateView.as_view(template_name='docs/chat-app.html'),
        name='chat-app'),
    url(r'^build-a-youtube-browser/$',
        TemplateView.as_view(template_name='docs/youtube-browser.html'),
        name='youtube-browser'),
    url(r'^run-react-native-on-device/$',
        TemplateView.as_view(template_name='docs/run-on-device.html'),
        name='run-on-device'),
    url(r'^faq/$',
        TemplateView.as_view(template_name='docs/faq.html'),
        name='faq'),
    url(r'^facebook-sdk/$',
        TemplateView.as_view(template_name='docs/facebook-sdk.html'),
        name='facebook-sdk'),
    url(r'^team-sharing/$',
        TemplateView.as_view(template_name='docs/team-sharing.html'),
        name='team-sharing'),
    url(r'^beta-testing/$',
        TemplateView.as_view(template_name='docs/beta-testing.html'),
        name='beta-testing'),
    url(r'^existing-react-native-app/$',
        TemplateView.as_view(
            template_name='docs/existing-react-native-app.html'),
        name='existing-react-native-app'),
    url(r'^base-version/$', BaseVersionView.as_view(), name='base-version')
]

siphon/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required


def static_url(regex, name, authenticated=False):
    view = TemplateView.as_view(template_name='%s.html' % name)
    if authenticated:
        view = login_required(view)
    return url(regex, view, name=name)

static_urls = [
    static_url(r'^$', 'landing'),
    static_url(r'^dashboard/$', 'dashboard', authenticated=True),
    static_url(r'^contact-us/$', 'contact'),
    static_url(r'^pricing/$', 'pricing'),
    static_url(r'^terms-of-use/$', 'terms-of-use'),
    static_url(r'^privacy-policy/$', 'privacy-policy'),
    static_url(r'^android-launch/$', 'android-launch')
]

urlpatterns = [
    url('', include(static_urls, namespace='static')),
    url(r'^docs/', include('siphon.web.apps.docs.urls',
        namespace='docs')),
    url(r'^accounts/', include('siphon.web.apps.accounts.urls',
        namespace='accounts')),
    url(r'^subscriptions/', include('siphon.web.apps.subscriptions.urls',
        namespace='subscriptions')),
    url(r'^analytics/', include('siphon.web.apps.analytics.urls',
        namespace='analytics')),
    url(r'^permissions/', include('siphon.web.apps.permissions.urls',
        namespace='permissions')),

    # API
    url(r'^api/v1/', include('siphon.web.api_urls', namespace='api')),

    # App Store shortcut alias
    url(r'^i/?$', RedirectView.as_view(
        url='https://itunes.apple.com/us/app/siphon-sandbox/id1059664078',
        permanent=False
    )),

    # Play Store shortcut alias
    url(r'^a/?$', RedirectView.as_view(
        url='https://play.google.com/store/apps/details?id=com.getsiphon.siphonbase',
        permanent=False
    )),

    # Third-party
    url(r'^drip/', include('drip.urls', namespace='drip')),

    # Here be dragons
    url(r'^bananas/', include(admin.site.urls))
]

siphon/web/apps/docs/views.py
from django.views.generic.base import TemplateView
from siphon.web.apps.apps.models import BaseVersion


class BaseVersionView(TemplateView):
    template_name = 'docs/base-version.html'

    def get_context_data(self, **kwargs):
        context = super(BaseVersionView, self).get_context_data(**kwargs)
        context['base_versions'] = BaseVersion.objects.all().order_by('-name')
        return context

templates/docs/includes/index.html
<div class="docs__index">
    <span class="docs__index__subheading">Fundamentals</span>
    <a href="{% url 'docs:quickstart' %}">Quickstart</a>
    <a href="{% url 'docs:faq' %}">FAQ</a>
    <a href="{% url 'docs:faq' %}#native-modules">Native modules</a>
    <a href="{% url 'docs:base-version' %}">Base versions</a>
    <a href="{% url 'docs:run-on-device' %}">Running on your device</a>
    <a href="{% url 'static:pricing' %}#how-does-publishing-work">How publishing works</a>
    <a href="{% url 'docs:faq' %}#assets">Assets</a>
    <a href="{% url 'docs:faq' %}#dot-siphonignore">Ignoring files</a>
    <a href="{% url 'docs:faq' %}#over-the-air-updates">Over-the-air updates</a>
    <a href="{% url 'docs:existing-react-native-app' %}">Convert an existing React Native app</a>

    <span class="docs__index__subheading">Sharing</span>
    <a href="{% url 'docs:beta-testing' %}">Beta testing</a>
    <a href="{% url 'docs:team-sharing' %}">Collaborating in a team</a>

    <span class="docs__index__subheading">Tutorials</span>
    <a href="{% url 'docs:chat-app' %}">Build a real-time chat app</a>
    <a href="{% url 'docs:youtube-browser' %}">Build a YouTube video browser</a>
    <a href="{% url 'docs:facebook-sdk' %}">Using Facebook's SDK with Siphon</a>
    <a href="{% url 'docs:existing-react-native-app' %}">Turn an existing React Native app into a Siphon app</a>

    <span class="docs__index__subheading">Siphon Sandbox</span>
    <a href="/i">iOS (App Store)</a>
    <a href="/a">Android (Google Play)</a>
</div>